import type { Metadata } from 'next';
import './globals.css';
import App from './app';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-Aeonik`}>
        <App>{children}</App>
      </body>
    </html>
  );
}
